//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Linq;
using System.Collections.Generic;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FinanceModel", "FK__Users__permenent__060DEAE8", "Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceApp.Data.Address), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.User), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__Users__presentad__07020F21", "Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceApp.Data.Address), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.User), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__collectio__loan___21B6055D", "Loan", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceApp.Data.Loan), "collection", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.collection), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__DailyIntr__loan___173876EA", "Loan", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceApp.Data.Loan), "DailyIntrest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.DailyIntrest), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__DailyIntr__suret__182C9B23", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FinanceApp.Data.User), "DailyIntrest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.DailyIntrest), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__Finance__loan_id__1CF15040", "Loan", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceApp.Data.Loan), "Finance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.Finance), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__Loan__approved__1273C1CD", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FinanceApp.Data.User), "Loan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.Loan), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__Loan__loantype_i__108B795B", "LoanType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceApp.Data.LoanType), "Loan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.Loan), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__Loan__user_id__0F975522", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceApp.Data.User), "Loan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.Loan), true)]
[assembly: EdmRelationshipAttribute("FinanceModel", "FK__LoanExtan__loan___267ABA7A", "Loan", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinanceApp.Data.Loan), "LoanExtantion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinanceApp.Data.LoanExtantion), true)]

#endregion

namespace FinanceApp.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FinanceAppEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FinanceAppEntities object using the connection string found in the 'FinanceAppEntities' section of the application configuration file.
        /// </summary>
        public FinanceAppEntities() : base("name=FinanceAppEntities", "FinanceAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FinanceAppEntities object.
        /// </summary>
        public FinanceAppEntities(string connectionString) : base(connectionString, "FinanceAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FinanceAppEntities object.
        /// </summary>
        public FinanceAppEntities(EntityConnection connection) : base(connection, "FinanceAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Address> Addresses
        {
            get
            {
                if ((_Addresses == null))
                {
                    _Addresses = base.CreateObjectSet<Address>("Addresses");
                }
                return _Addresses;
            }
        }
        private ObjectSet<Address> _Addresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<collection> collections
        {
            get
            {
                if ((_collections == null))
                {
                    _collections = base.CreateObjectSet<collection>("collections");
                }
                return _collections;
            }
        }
        private ObjectSet<collection> _collections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DailyIntrest> DailyIntrests
        {
            get
            {
                if ((_DailyIntrests == null))
                {
                    _DailyIntrests = base.CreateObjectSet<DailyIntrest>("DailyIntrests");
                }
                return _DailyIntrests;
            }
        }
        private ObjectSet<DailyIntrest> _DailyIntrests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Finance> Finances
        {
            get
            {
                if ((_Finances == null))
                {
                    _Finances = base.CreateObjectSet<Finance>("Finances");
                }
                return _Finances;
            }
        }
        private ObjectSet<Finance> _Finances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Loan> Loans
        {
            get
            {
                if ((_Loans == null))
                {
                    _Loans = base.CreateObjectSet<Loan>("Loans");
                }
                return _Loans;
            }
        }
        private ObjectSet<Loan> _Loans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoanExtantion> LoanExtantions
        {
            get
            {
                if ((_LoanExtantions == null))
                {
                    _LoanExtantions = base.CreateObjectSet<LoanExtantion>("LoanExtantions");
                }
                return _LoanExtantions;
            }
        }
        private ObjectSet<LoanExtantion> _LoanExtantions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoanType> LoanTypes
        {
            get
            {
                if ((_LoanTypes == null))
                {
                    _LoanTypes = base.CreateObjectSet<LoanType>("LoanTypes");
                }
                return _LoanTypes;
            }
        }
        private ObjectSet<LoanType> _LoanTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Addresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddresses(Address address)
        {
            base.AddObject("Addresses", address);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the collections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocollections(collection collection)
        {
            base.AddObject("collections", collection);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DailyIntrests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDailyIntrests(DailyIntrest dailyIntrest)
        {
            base.AddObject("DailyIntrests", dailyIntrest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Finances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFinances(Finance finance)
        {
            base.AddObject("Finances", finance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Loans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoans(Loan loan)
        {
            base.AddObject("Loans", loan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoanExtantions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoanExtantions(LoanExtantion loanExtantion)
        {
            base.AddObject("LoanExtantions", loanExtantion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoanTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoanTypes(LoanType loanType)
        {
            base.AddObject("LoanTypes", loanType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="Address")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Address : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="address1">Initial value of the address1 property.</param>
        public static Address CreateAddress(global::System.Int32 id, global::System.String address1)
        {
            Address address = new Address();
            address.id = id;
            address.address1 = address1;
            return address;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address1
        {
            get
            {
                return _address1;
            }
            set
            {
                Onaddress1Changing(value);
                ReportPropertyChanging("address1");
                _address1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address1");
                Onaddress1Changed();
            }
        }
        private global::System.String _address1;
        partial void Onaddress1Changing(global::System.String value);
        partial void Onaddress1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Users__permenent__060DEAE8", "Users")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("FinanceModel.FK__Users__permenent__060DEAE8", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("FinanceModel.FK__Users__permenent__060DEAE8", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Users__presentad__07020F21", "Users")]
        public EntityCollection<User> Users1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("FinanceModel.FK__Users__presentad__07020F21", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("FinanceModel.FK__Users__presentad__07020F21", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="collection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class collection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new collection object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="loan_id">Initial value of the loan_id property.</param>
        /// <param name="collectiondate">Initial value of the collectiondate property.</param>
        /// <param name="amoutn">Initial value of the amoutn property.</param>
        public static collection Createcollection(global::System.Int32 id, global::System.Int32 loan_id, global::System.DateTime collectiondate, global::System.Int32 amoutn)
        {
            collection collection = new collection();
            collection.id = id;
            collection.loan_id = loan_id;
            collection.collectiondate = collectiondate;
            collection.amoutn = amoutn;
            return collection;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loan_id
        {
            get
            {
                return _loan_id;
            }
            set
            {
                Onloan_idChanging(value);
                ReportPropertyChanging("loan_id");
                _loan_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("loan_id");
                Onloan_idChanged();
            }
        }
        private global::System.Int32 _loan_id;
        partial void Onloan_idChanging(global::System.Int32 value);
        partial void Onloan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime collectiondate
        {
            get
            {
                return _collectiondate;
            }
            set
            {
                OncollectiondateChanging(value);
                ReportPropertyChanging("collectiondate");
                _collectiondate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("collectiondate");
                OncollectiondateChanged();
            }
        }
        private global::System.DateTime _collectiondate;
        partial void OncollectiondateChanging(global::System.DateTime value);
        partial void OncollectiondateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 amoutn
        {
            get
            {
                return _amoutn;
            }
            set
            {
                OnamoutnChanging(value);
                ReportPropertyChanging("amoutn");
                _amoutn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amoutn");
                OnamoutnChanged();
            }
        }
        private global::System.Int32 _amoutn;
        partial void OnamoutnChanging(global::System.Int32 value);
        partial void OnamoutnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__collectio__loan___21B6055D", "Loan")]
        public Loan Loan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__collectio__loan___21B6055D", "Loan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__collectio__loan___21B6055D", "Loan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Loan> LoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__collectio__loan___21B6055D", "Loan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Loan>("FinanceModel.FK__collectio__loan___21B6055D", "Loan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="DailyIntrest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DailyIntrest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DailyIntrest object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="loan_id">Initial value of the loan_id property.</param>
        public static DailyIntrest CreateDailyIntrest(global::System.Int32 id, global::System.Int32 loan_id)
        {
            DailyIntrest dailyIntrest = new DailyIntrest();
            dailyIntrest.id = id;
            dailyIntrest.loan_id = loan_id;
            return dailyIntrest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loan_id
        {
            get
            {
                return _loan_id;
            }
            set
            {
                Onloan_idChanging(value);
                ReportPropertyChanging("loan_id");
                _loan_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("loan_id");
                Onloan_idChanged();
            }
        }
        private global::System.Int32 _loan_id;
        partial void Onloan_idChanging(global::System.Int32 value);
        partial void Onloan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> surety
        {
            get
            {
                return _surety;
            }
            set
            {
                OnsuretyChanging(value);
                ReportPropertyChanging("surety");
                _surety = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("surety");
                OnsuretyChanged();
            }
        }
        private Nullable<global::System.Int32> _surety;
        partial void OnsuretyChanging(Nullable<global::System.Int32> value);
        partial void OnsuretyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__DailyIntr__loan___173876EA", "Loan")]
        public Loan Loan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__DailyIntr__loan___173876EA", "Loan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__DailyIntr__loan___173876EA", "Loan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Loan> LoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__DailyIntr__loan___173876EA", "Loan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Loan>("FinanceModel.FK__DailyIntr__loan___173876EA", "Loan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__DailyIntr__suret__182C9B23", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__DailyIntr__suret__182C9B23", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__DailyIntr__suret__182C9B23", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__DailyIntr__suret__182C9B23", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("FinanceModel.FK__DailyIntr__suret__182C9B23", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="Finance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Finance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Finance object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="loan_id">Initial value of the loan_id property.</param>
        /// <param name="duedate">Initial value of the duedate property.</param>
        /// <param name="period">Initial value of the period property.</param>
        public static Finance CreateFinance(global::System.Int32 id, global::System.Int32 loan_id, global::System.DateTime duedate, global::System.Int32 period)
        {
            Finance finance = new Finance();
            finance.id = id;
            finance.loan_id = loan_id;
            finance.duedate = duedate;
            finance.period = period;
            return finance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loan_id
        {
            get
            {
                return _loan_id;
            }
            set
            {
                Onloan_idChanging(value);
                ReportPropertyChanging("loan_id");
                _loan_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("loan_id");
                Onloan_idChanged();
            }
        }
        private global::System.Int32 _loan_id;
        partial void Onloan_idChanging(global::System.Int32 value);
        partial void Onloan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime duedate
        {
            get
            {
                return _duedate;
            }
            set
            {
                OnduedateChanging(value);
                ReportPropertyChanging("duedate");
                _duedate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duedate");
                OnduedateChanged();
            }
        }
        private global::System.DateTime _duedate;
        partial void OnduedateChanging(global::System.DateTime value);
        partial void OnduedateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 period
        {
            get
            {
                return _period;
            }
            set
            {
                OnperiodChanging(value);
                ReportPropertyChanging("period");
                _period = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("period");
                OnperiodChanged();
            }
        }
        private global::System.Int32 _period;
        partial void OnperiodChanging(global::System.Int32 value);
        partial void OnperiodChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Finance__loan_id__1CF15040", "Loan")]
        public Loan Loan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__Finance__loan_id__1CF15040", "Loan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__Finance__loan_id__1CF15040", "Loan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Loan> LoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__Finance__loan_id__1CF15040", "Loan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Loan>("FinanceModel.FK__Finance__loan_id__1CF15040", "Loan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="Loan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Loan : EntityObject
    {
        #region Factory Method
        public static FinanceAppEntities entity = new FinanceAppEntities();
        /// <summary>
        /// Create a new Loan object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="loantype_id">Initial value of the loantype_id property.</param>
        /// <param name="amoutn">Initial value of the amoutn property.</param>
        /// <param name="intrest">Initial value of the intrest property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="startdate">Initial value of the startdate property.</param>
        /// <param name="enddate">Initial value of the enddate property.</param>
        public static Loan CreateLoan(global::System.Int32 id, global::System.Int32 user_id, global::System.Int32 loantype_id, global::System.Int32 amoutn, global::System.Int32 intrest, global::System.Boolean status, global::System.DateTime startdate, global::System.DateTime enddate)
        {
            Loan loan = new Loan();
            loan.id = id;
            loan.user_id = user_id;
            loan.loantype_id = loantype_id;
            loan.amoutn = amoutn;
            loan.intrest = intrest;
            loan.status = status;
            loan.startdate = startdate;
            loan.enddate = enddate;
            return loan;
        }

        public static int getLoanMaxID()
        {
            Loan loan = entity.Loans.OrderByDescending(u => u.id).FirstOrDefault();
            if (loan != null)
            {
                return loan.id;
            }
            return 0;
        }

        public static IList<Loan> getUserLoanDetails(User user)
        {
            IList<Loan> loans;
            var loanquery = from loan in entity.Loans
                            where loan.user_id == user.id
                            select loan;
            loans = loanquery.ToList<Loan>();
            return loans;
        }

        public static void saveLoan(int user_id,
            int authrized_user_id,
            int surity_id,
            int intrest,
            int amount,
            bool status,
            int loan_type,
            DateTime startdate,
            DateTime enddate,
            int period = 0,
            DateTime duedate = new DateTime())
        {
            Loan loan = new Loan();
            loan.intrest = intrest;
            loan.amoutn = amount;
            loan.status = status;
            loan.user_id = user_id;
            loan.approved = authrized_user_id;
            loan.startdate = startdate;
            loan.enddate = enddate;
            loan.loantype_id = loan_type;
            entity.AddToLoans(loan);
            if (loan_type == 1)
            {
                DailyIntrest dailyIntrest = new DailyIntrest();
                dailyIntrest.loan_id = loan.id;
                dailyIntrest.surety = surity_id;
                entity.AddToDailyIntrests(dailyIntrest);
            }
            else
            {
                Finance finance = new Finance();
                finance.duedate = duedate;
                finance.loan_id = loan.id;
                finance.period = period;
                entity.AddToFinances(finance);
            }
            entity.SaveChanges();
        }
        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [System.ComponentModel.DisplayName("Loan Number") ]
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loantype_id
        {
            get
            {
                return _loantype_id;
            }
            set
            {
                Onloantype_idChanging(value);
                ReportPropertyChanging("loantype_id");
                _loantype_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("loantype_id");
                Onloantype_idChanged();
            }
        }
        private global::System.Int32 _loantype_id;
        partial void Onloantype_idChanging(global::System.Int32 value);
        partial void Onloantype_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 amoutn
        {
            get
            {
                return _amoutn;
            }
            set
            {
                OnamoutnChanging(value);
                ReportPropertyChanging("amoutn");
                _amoutn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amoutn");
                OnamoutnChanged();
            }
        }
        private global::System.Int32 _amoutn;
        partial void OnamoutnChanging(global::System.Int32 value);
        partial void OnamoutnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 intrest
        {
            get
            {
                return _intrest;
            }
            set
            {
                OnintrestChanging(value);
                ReportPropertyChanging("intrest");
                _intrest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("intrest");
                OnintrestChanged();
            }
        }
        private global::System.Int32 _intrest;
        partial void OnintrestChanging(global::System.Int32 value);
        partial void OnintrestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Boolean _status;
        partial void OnstatusChanging(global::System.Boolean value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime startdate
        {
            get
            {
                return _startdate;
            }
            set
            {
                OnstartdateChanging(value);
                ReportPropertyChanging("startdate");
                _startdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startdate");
                OnstartdateChanged();
            }
        }
        private global::System.DateTime _startdate;
        partial void OnstartdateChanging(global::System.DateTime value);
        partial void OnstartdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime enddate
        {
            get
            {
                return _enddate;
            }
            set
            {
                OnenddateChanging(value);
                ReportPropertyChanging("enddate");
                _enddate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("enddate");
                OnenddateChanged();
            }
        }
        private global::System.DateTime _enddate;
        partial void OnenddateChanging(global::System.DateTime value);
        partial void OnenddateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> approved
        {
            get
            {
                return _approved;
            }
            set
            {
                OnapprovedChanging(value);
                ReportPropertyChanging("approved");
                _approved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("approved");
                OnapprovedChanged();
            }
        }
        private Nullable<global::System.Int32> _approved;
        partial void OnapprovedChanging(Nullable<global::System.Int32> value);
        partial void OnapprovedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__collectio__loan___21B6055D", "collection")]
        public EntityCollection<collection> collections
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<collection>("FinanceModel.FK__collectio__loan___21B6055D", "collection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<collection>("FinanceModel.FK__collectio__loan___21B6055D", "collection", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__DailyIntr__loan___173876EA", "DailyIntrest")]
        public EntityCollection<DailyIntrest> DailyIntrests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DailyIntrest>("FinanceModel.FK__DailyIntr__loan___173876EA", "DailyIntrest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DailyIntrest>("FinanceModel.FK__DailyIntr__loan___173876EA", "DailyIntrest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Finance__loan_id__1CF15040", "Finance")]
        public EntityCollection<Finance> Finances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Finance>("FinanceModel.FK__Finance__loan_id__1CF15040", "Finance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Finance>("FinanceModel.FK__Finance__loan_id__1CF15040", "Finance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Loan__approved__1273C1CD", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__Loan__approved__1273C1CD", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__Loan__approved__1273C1CD", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__Loan__approved__1273C1CD", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("FinanceModel.FK__Loan__approved__1273C1CD", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Loan__loantype_i__108B795B", "LoanType")]
        public LoanType LoanType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoanType>("FinanceModel.FK__Loan__loantype_i__108B795B", "LoanType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoanType>("FinanceModel.FK__Loan__loantype_i__108B795B", "LoanType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LoanType> LoanTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoanType>("FinanceModel.FK__Loan__loantype_i__108B795B", "LoanType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LoanType>("FinanceModel.FK__Loan__loantype_i__108B795B", "LoanType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Loan__user_id__0F975522", "Users")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__Loan__user_id__0F975522", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__Loan__user_id__0F975522", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("FinanceModel.FK__Loan__user_id__0F975522", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("FinanceModel.FK__Loan__user_id__0F975522", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__LoanExtan__loan___267ABA7A", "LoanExtantion")]
        public EntityCollection<LoanExtantion> LoanExtantions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LoanExtantion>("FinanceModel.FK__LoanExtan__loan___267ABA7A", "LoanExtantion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LoanExtantion>("FinanceModel.FK__LoanExtan__loan___267ABA7A", "LoanExtantion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="LoanExtantion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoanExtantion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoanExtantion object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="loan_id">Initial value of the loan_id property.</param>
        /// <param name="extendeddate">Initial value of the extendeddate property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="extracharge">Initial value of the extracharge property.</param>
        public static LoanExtantion CreateLoanExtantion(global::System.Int32 id, global::System.Int32 loan_id, global::System.DateTime extendeddate, global::System.String description, global::System.Int32 extracharge)
        {
            LoanExtantion loanExtantion = new LoanExtantion();
            loanExtantion.id = id;
            loanExtantion.loan_id = loan_id;
            loanExtantion.extendeddate = extendeddate;
            loanExtantion.description = description;
            loanExtantion.extracharge = extracharge;
            return loanExtantion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loan_id
        {
            get
            {
                return _loan_id;
            }
            set
            {
                Onloan_idChanging(value);
                ReportPropertyChanging("loan_id");
                _loan_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("loan_id");
                Onloan_idChanged();
            }
        }
        private global::System.Int32 _loan_id;
        partial void Onloan_idChanging(global::System.Int32 value);
        partial void Onloan_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime extendeddate
        {
            get
            {
                return _extendeddate;
            }
            set
            {
                OnextendeddateChanging(value);
                ReportPropertyChanging("extendeddate");
                _extendeddate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("extendeddate");
                OnextendeddateChanged();
            }
        }
        private global::System.DateTime _extendeddate;
        partial void OnextendeddateChanging(global::System.DateTime value);
        partial void OnextendeddateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 extracharge
        {
            get
            {
                return _extracharge;
            }
            set
            {
                OnextrachargeChanging(value);
                ReportPropertyChanging("extracharge");
                _extracharge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("extracharge");
                OnextrachargeChanged();
            }
        }
        private global::System.Int32 _extracharge;
        partial void OnextrachargeChanging(global::System.Int32 value);
        partial void OnextrachargeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__LoanExtan__loan___267ABA7A", "Loan")]
        public Loan Loan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__LoanExtan__loan___267ABA7A", "Loan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__LoanExtan__loan___267ABA7A", "Loan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Loan> LoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loan>("FinanceModel.FK__LoanExtan__loan___267ABA7A", "Loan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Loan>("FinanceModel.FK__LoanExtan__loan___267ABA7A", "Loan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="LoanType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoanType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoanType object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="typename">Initial value of the typename property.</param>
        public static LoanType CreateLoanType(global::System.Int32 id, global::System.String typename)
        {
            LoanType loanType = new LoanType();
            loanType.id = id;
            loanType.typename = typename;
            return loanType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String typename
        {
            get
            {
                return _typename;
            }
            set
            {
                OntypenameChanging(value);
                ReportPropertyChanging("typename");
                _typename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("typename");
                OntypenameChanged();
            }
        }
        private global::System.String _typename;
        partial void OntypenameChanging(global::System.String value);
        partial void OntypenameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Loan__loantype_i__108B795B", "Loan")]
        public EntityCollection<Loan> Loans
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Loan>("FinanceModel.FK__Loan__loantype_i__108B795B", "Loan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Loan>("FinanceModel.FK__Loan__loantype_i__108B795B", "Loan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinanceModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method

        public static FinanceAppEntities entity = new FinanceAppEntities();
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="permenentaddr">Initial value of the permenentaddr property.</param>
        /// <param name="presentaddr">Initial value of the presentaddr property.</param>
        /// <param name="role">Initial value of the role property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String name, global::System.Int32 permenentaddr, global::System.Int32 presentaddr, global::System.String role)
        {
            User user = new User();
            user.id = id;
            user.name = name;
            user.permenentaddr = permenentaddr;
            user.presentaddr = presentaddr;
            user.role = role;
            return user;
        }

        /// < summary>
        /// Methods for handaling the user details
        /// </summary>
        public static IList<User> getAllUsers()
        {
            var users = from user in entity.Users
                        select user;
            IList<User> courseList = users.ToList<User>();
            return courseList;
        }

        /// < summary>
        /// Mehod to Save user details 
        /// </summary>
        public static void saveUser(string address,
            string name,
            string occupation,
            int phone,
            int income,
            int limit,
            string email,
            string role = "User")
        {
            Data.Address adds = new Data.Address();
            User user = new User();
            adds.address1 = address;
            entity.AddToAddresses(adds);
            user.name = name;
            user.occupation = occupation;
            user.phone = phone;
            user.presentaddr = adds.id;
            user.permenentaddr = adds.id;
            user.income = income;
            user.limit = limit;
            user.email = email;
            user.role = role;
            entity.AddToUsers(user);
            entity.SaveChanges();
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 permenentaddr
        {
            get
            {
                return _permenentaddr;
            }
            set
            {
                OnpermenentaddrChanging(value);
                ReportPropertyChanging("permenentaddr");
                _permenentaddr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("permenentaddr");
                OnpermenentaddrChanged();
            }
        }
        private global::System.Int32 _permenentaddr;
        partial void OnpermenentaddrChanging(global::System.Int32 value);
        partial void OnpermenentaddrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 presentaddr
        {
            get
            {
                return _presentaddr;
            }
            set
            {
                OnpresentaddrChanging(value);
                ReportPropertyChanging("presentaddr");
                _presentaddr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("presentaddr");
                OnpresentaddrChanged();
            }
        }
        private global::System.Int32 _presentaddr;
        partial void OnpresentaddrChanging(global::System.Int32 value);
        partial void OnpresentaddrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private Nullable<global::System.Int32> _phone;
        partial void OnphoneChanging(Nullable<global::System.Int32> value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String occupation
        {
            get
            {
                return _occupation;
            }
            set
            {
                OnoccupationChanging(value);
                ReportPropertyChanging("occupation");
                _occupation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("occupation");
                OnoccupationChanged();
            }
        }
        private global::System.String _occupation;
        partial void OnoccupationChanging(global::System.String value);
        partial void OnoccupationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> income
        {
            get
            {
                return _income;
            }
            set
            {
                OnincomeChanging(value);
                ReportPropertyChanging("income");
                _income = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("income");
                OnincomeChanged();
            }
        }
        private Nullable<global::System.Int32> _income;
        partial void OnincomeChanging(Nullable<global::System.Int32> value);
        partial void OnincomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> limit
        {
            get
            {
                return _limit;
            }
            set
            {
                OnlimitChanging(value);
                ReportPropertyChanging("limit");
                _limit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("limit");
                OnlimitChanged();
            }
        }
        private Nullable<global::System.Int32> _limit;
        partial void OnlimitChanging(Nullable<global::System.Int32> value);
        partial void OnlimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String role
        {
            get
            {
                return _role;
            }
            set
            {
                OnroleChanging(value);
                ReportPropertyChanging("role");
                _role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("role");
                OnroleChanged();
            }
        }
        private global::System.String _role;
        partial void OnroleChanging(global::System.String value);
        partial void OnroleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] image
        {
            get
            {
                return StructuralObject.GetValidValue(_image);
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.Byte[] _image;
        partial void OnimageChanging(global::System.Byte[] value);
        partial void OnimageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Users__permenent__060DEAE8", "Address")]
        public Address Address
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("FinanceModel.FK__Users__permenent__060DEAE8", "Address").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("FinanceModel.FK__Users__permenent__060DEAE8", "Address").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Address> AddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("FinanceModel.FK__Users__permenent__060DEAE8", "Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Address>("FinanceModel.FK__Users__permenent__060DEAE8", "Address", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Users__presentad__07020F21", "Address")]
        public Address Address1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("FinanceModel.FK__Users__presentad__07020F21", "Address").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("FinanceModel.FK__Users__presentad__07020F21", "Address").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Address> Address1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("FinanceModel.FK__Users__presentad__07020F21", "Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Address>("FinanceModel.FK__Users__presentad__07020F21", "Address", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__DailyIntr__suret__182C9B23", "DailyIntrest")]
        public EntityCollection<DailyIntrest> DailyIntrests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DailyIntrest>("FinanceModel.FK__DailyIntr__suret__182C9B23", "DailyIntrest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DailyIntrest>("FinanceModel.FK__DailyIntr__suret__182C9B23", "DailyIntrest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Loan__approved__1273C1CD", "Loan")]
        public EntityCollection<Loan> Loans
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Loan>("FinanceModel.FK__Loan__approved__1273C1CD", "Loan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Loan>("FinanceModel.FK__Loan__approved__1273C1CD", "Loan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinanceModel", "FK__Loan__user_id__0F975522", "Loan")]
        public EntityCollection<Loan> Loans1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Loan>("FinanceModel.FK__Loan__user_id__0F975522", "Loan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Loan>("FinanceModel.FK__Loan__user_id__0F975522", "Loan", value);
                }
            }
        }

        #endregion



    }

    #endregion
    
}
